Update superlinter.yml
Error: *Error: Unable to resolve action `actions/checkout@v4`, unable to find version `v4`. Unable to resolve action `github/super-linter@4`, unable to find version `4`*  
Change to @3.17.0